<?php

namespace App\Tests\Controller\Api;

use App\Entity\Graine;
use App\Entity\GraineLot;
use App\Entity\GraineType;
use App\Entity\Utilisateur;
use App\Tests\DatabaseTestCase;

/**
 * Tests fonctionnels du CRUD JSON des graines concrètes (grainothèque).
 */
class GraineApiTest extends DatabaseTestCase
{
    private function json(string $method, string $uri, array $payload = null): array
    {
        $this->client->request(
            $method,
            $uri,
            server: ['CONTENT_TYPE' => 'application/json'],
            content: null !== $payload ? json_encode($payload) : null,
        );
        $content = $this->client->getResponse()->getContent();

        return '' !== $content ? (json_decode($content, true) ?? []) : [];
    }

    private function makeGraineType(Utilisateur $user, string $name = 'Tomate Cerise', string $code = 'TC', ?GraineType $parent = null): GraineType
    {
        $gt = (new GraineType())->setName($name)->setCode($code)->setUtilisateur($user)->setParent($parent);
        $this->em->persist($gt);
        $this->em->flush();

        return $gt;
    }

    private function makeGraine(Utilisateur $user, GraineType $gt, string $code, string $name = 'Sweet'): Graine
    {
        $g = (new Graine())->setGraineType($gt)->setCode($code)->setName($name)->setUtilisateur($user);
        $this->em->persist($g);
        $this->em->flush();

        return $g;
    }

    private function addLot(Utilisateur $user, Graine $graine, int $quantiteRestante): GraineLot
    {
        $lot = (new GraineLot())
            ->setGraine($graine)
            ->setUtilisateur($user)
            ->setSource('achat')
            ->setDateAcquisition(new \DateTimeImmutable('2026-01-01'))
            ->setQuantiteInitiale($quantiteRestante)
            ->setQuantiteRestante($quantiteRestante);
        $this->em->persist($lot);
        $this->em->flush();

        return $lot;
    }

    public function testListRequiresAuth(): void
    {
        $this->client->request('GET', '/api/graines');
        $this->assertResponseStatusCodeSame(401);
    }

    public function testCreateWithGraineType(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice);
        $this->client->loginUser($alice);

        $created = $this->json('POST', '/api/graines', [
            'graineType' => $gt->getId(),
            'name' => 'Sweet',
            'code' => 'TC1',
            'methodeSemisConseillee' => 'couvert',
        ]);
        $this->assertResponseStatusCodeSame(201);
        $this->assertSame('TC1', $created['code']);
        $this->assertSame('Sweet', $created['name']);
        $this->assertSame($gt->getId(), $created['graineType']['id']);
        $this->assertSame('couvert', $created['methodeSemisConseillee']);
    }

    public function testCodeAutoGeneratedWhenEmpty(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice, 'Tomate Cerise', 'TC');
        $this->makeGraine($alice, $gt, 'TC1');
        $this->makeGraine($alice, $gt, 'TC2');
        $this->client->loginUser($alice);

        $created = $this->json('POST', '/api/graines', ['graineType' => $gt->getId(), 'name' => 'Sweet']);
        $this->assertResponseStatusCodeSame(201);
        $this->assertSame('TC3', $created['code']);
    }

    public function testNextCodeEndpoint(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice, 'Tomate Cerise', 'TC');
        $this->makeGraine($alice, $gt, 'TC1');
        $this->client->loginUser($alice);

        $data = $this->json('GET', '/api/graines/next-code?graineType='.$gt->getId());
        $this->assertSame('TC2', $data['code']);
    }

    public function testCreateWithoutGraineTypeReturns422(): void
    {
        $alice = $this->createUser('alice');
        $this->client->loginUser($alice);

        $data = $this->json('POST', '/api/graines', ['name' => 'Sweet', 'code' => 'X1']);
        $this->assertResponseStatusCodeSame(422);
        $this->assertArrayHasKey('graineType', $data['errors']);
    }

    public function testDuplicateCodeReturns422(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice);
        $this->makeGraine($alice, $gt, 'TC1');
        $this->client->loginUser($alice);

        $data = $this->json('POST', '/api/graines', ['graineType' => $gt->getId(), 'name' => 'Autre', 'code' => 'TC1']);
        $this->assertResponseStatusCodeSame(422);
        $this->assertArrayHasKey('code', $data['errors']);
    }

    public function testInvalidMethodeReturns422(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice);
        $this->client->loginUser($alice);

        $data = $this->json('POST', '/api/graines', [
            'graineType' => $gt->getId(),
            'name' => 'Sweet',
            'methodeSemisConseillee' => 'godet',
        ]);
        $this->assertResponseStatusCodeSame(422);
        $this->assertArrayHasKey('methodeSemisConseillee', $data['errors']);
    }

    public function testListFilteredByGraineType(): void
    {
        $alice = $this->createUser('alice');
        $gt1 = $this->makeGraineType($alice, 'Tomate Cerise', 'TC');
        $gt2 = $this->makeGraineType($alice, 'Courge', 'CG');
        $this->makeGraine($alice, $gt1, 'TC1');
        $this->makeGraine($alice, $gt2, 'CG1');
        $this->client->loginUser($alice);

        $list = $this->json('GET', '/api/graines?graineType='.$gt1->getId());
        $this->assertCount(1, $list['items']);
        $this->assertSame('TC1', $list['items'][0]['code']);
    }

    public function testListFilteredByTypeIncludesDescendants(): void
    {
        $alice = $this->createUser('alice');
        $pois = $this->makeGraineType($alice, 'Pois', 'P');
        $nain = $this->makeGraineType($alice, 'Pois nain', 'PN', $pois);
        $rame = $this->makeGraineType($alice, 'Pois à rame', 'PR', $pois);
        $courge = $this->makeGraineType($alice, 'Courge', 'CG');
        $this->makeGraine($alice, $pois, 'P1');
        $this->makeGraine($alice, $nain, 'PN1');
        $this->makeGraine($alice, $rame, 'PR1');
        $this->makeGraine($alice, $courge, 'CG1');
        $this->client->loginUser($alice);

        // Filtrer par le parent « Pois » remonte le parent + ses deux sous-types.
        $list = $this->json('GET', '/api/graines?graineType='.$pois->getId());
        $codes = array_column($list['items'], 'code');
        sort($codes);
        $this->assertSame(['P1', 'PN1', 'PR1'], $codes);

        // Filtrer par l'enfant ne retourne que la sienne.
        $list = $this->json('GET', '/api/graines?graineType='.$nain->getId());
        $this->assertSame(['PN1'], array_column($list['items'], 'code'));
    }

    public function testListScopedToOwner(): void
    {
        $alice = $this->createUser('alice');
        $bob = $this->createUser('bob');
        $gtA = $this->makeGraineType($alice, 'Type Alice', 'TA');
        $gtB = $this->makeGraineType($bob, 'Type Bob', 'TB');
        $this->makeGraine($alice, $gtA, 'TA1');
        $this->makeGraine($bob, $gtB, 'TB1');

        $this->client->loginUser($alice);
        $list = $this->json('GET', '/api/graines');
        $codes = array_column($list['items'], 'code');
        $this->assertContains('TA1', $codes);
        $this->assertNotContains('TB1', $codes);
    }

    public function testListSearchByText(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice, 'Tomate Cerise', 'TC');
        $this->makeGraine($alice, $gt, 'TC1', 'Sweet Million');
        $this->makeGraine($alice, $gt, 'TC2', 'Black Cherry');
        $this->client->loginUser($alice);

        // Recherche par nom.
        $list = $this->json('GET', '/api/graines?q=cherry');
        $this->assertCount(1, $list['items']);
        $this->assertSame('TC2', $list['items'][0]['code']);

        // Recherche par code.
        $list = $this->json('GET', '/api/graines?q=TC1');
        $this->assertCount(1, $list['items']);
        $this->assertSame('Sweet Million', $list['items'][0]['name']);

        // Recherche par nom de type (couvre les deux graines).
        $list = $this->json('GET', '/api/graines?q=tomate');
        $this->assertCount(2, $list['items']);
    }

    public function testListFilteredByStock(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice);
        $rachat = $this->makeGraine($alice, $gt, 'TC1', 'Rachat'); // 0 → à racheter
        $faible = $this->makeGraine($alice, $gt, 'TC2', 'Faible');
        $ok = $this->makeGraine($alice, $gt, 'TC3', 'Ok');
        $this->addLot($alice, $faible, 5);   // 1..10 → faible
        $this->addLot($alice, $ok, 8);
        $this->addLot($alice, $ok, 50);      // total 58 → en quantité
        $this->client->loginUser($alice);

        $rachatList = $this->json('GET', '/api/graines?stock=rachat');
        $this->assertSame(['TC1'], array_column($rachatList['items'], 'code'));

        $faibleList = $this->json('GET', '/api/graines?stock=faible');
        $this->assertSame(['TC2'], array_column($faibleList['items'], 'code'));

        $okList = $this->json('GET', '/api/graines?stock=ok');
        $this->assertSame(['TC3'], array_column($okList['items'], 'code'));
        $this->assertSame(58, $okList['items'][0]['stockRestant']);
    }

    public function testListPagination(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice);
        for ($i = 1; $i <= 25; ++$i) {
            $this->makeGraine($alice, $gt, sprintf('TC%02d', $i), 'Graine '.$i);
        }
        $this->client->loginUser($alice);

        $p1 = $this->json('GET', '/api/graines');
        $this->assertSame(25, $p1['total']);
        $this->assertSame(2, $p1['pages']);
        $this->assertSame(1, $p1['page']);
        $this->assertCount(20, $p1['items']);

        $p2 = $this->json('GET', '/api/graines?page=2');
        $this->assertSame(2, $p2['page']);
        $this->assertCount(5, $p2['items']);
    }

    public function testCannotEditOthers(): void
    {
        $alice = $this->createUser('alice');
        $bob = $this->createUser('bob');
        $gt = $this->makeGraineType($alice);
        $g = $this->makeGraine($alice, $gt, 'TC1');

        $this->client->loginUser($bob);
        $this->client->request(
            'PUT',
            '/api/graines/'.$g->getId(),
            server: ['CONTENT_TYPE' => 'application/json'],
            content: json_encode(['graineType' => $gt->getId(), 'name' => 'Piraté', 'code' => 'TC1']),
        );
        $this->assertResponseStatusCodeSame(403);
    }

    public function testUpdateAndDelete(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice);
        $g = $this->makeGraine($alice, $gt, 'TC1', 'Sweet');
        $id = $g->getId();
        $this->client->loginUser($alice);

        $updated = $this->json('PUT', '/api/graines/'.$id, [
            'graineType' => $gt->getId(),
            'name' => 'Sweet Million',
            'code' => 'TC1',
        ]);
        $this->assertResponseIsSuccessful();
        $this->assertSame('Sweet Million', $updated['name']);

        $this->client->request('DELETE', '/api/graines/'.$id);
        $this->assertResponseStatusCodeSame(204);

        $this->client->request('GET', '/api/graines/'.$id);
        $this->assertResponseStatusCodeSame(404);
    }
}
