<?php

namespace App\Tests\Controller\Api;

use App\Entity\Graine;
use App\Entity\GraineType;
use App\Entity\Utilisateur;
use App\Tests\DatabaseTestCase;

/**
 * Tests fonctionnels du CRUD JSON des graines concrètes (grainothèque).
 */
class GraineApiTest extends DatabaseTestCase
{
    private function json(string $method, string $uri, array $payload = null): array
    {
        $this->client->request(
            $method,
            $uri,
            server: ['CONTENT_TYPE' => 'application/json'],
            content: null !== $payload ? json_encode($payload) : null,
        );
        $content = $this->client->getResponse()->getContent();

        return '' !== $content ? (json_decode($content, true) ?? []) : [];
    }

    private function makeGraineType(Utilisateur $user, string $name = 'Tomate Cerise', string $code = 'TC'): GraineType
    {
        $gt = (new GraineType())->setName($name)->setCode($code)->setUtilisateur($user);
        $this->em->persist($gt);
        $this->em->flush();

        return $gt;
    }

    private function makeGraine(Utilisateur $user, GraineType $gt, string $code, string $name = 'Sweet'): Graine
    {
        $g = (new Graine())->setGraineType($gt)->setCode($code)->setName($name)->setUtilisateur($user);
        $this->em->persist($g);
        $this->em->flush();

        return $g;
    }

    public function testListRequiresAuth(): void
    {
        $this->client->request('GET', '/api/graines');
        $this->assertResponseStatusCodeSame(401);
    }

    public function testCreateWithGraineType(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice);
        $this->client->loginUser($alice);

        $created = $this->json('POST', '/api/graines', [
            'graineType' => $gt->getId(),
            'name' => 'Sweet',
            'code' => 'TC1',
            'methodeSemisConseillee' => 'couvert',
        ]);
        $this->assertResponseStatusCodeSame(201);
        $this->assertSame('TC1', $created['code']);
        $this->assertSame('Sweet', $created['name']);
        $this->assertSame($gt->getId(), $created['graineType']['id']);
        $this->assertSame('couvert', $created['methodeSemisConseillee']);
    }

    public function testCodeAutoGeneratedWhenEmpty(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice, 'Tomate Cerise', 'TC');
        $this->makeGraine($alice, $gt, 'TC1');
        $this->makeGraine($alice, $gt, 'TC2');
        $this->client->loginUser($alice);

        $created = $this->json('POST', '/api/graines', ['graineType' => $gt->getId(), 'name' => 'Sweet']);
        $this->assertResponseStatusCodeSame(201);
        $this->assertSame('TC3', $created['code']);
    }

    public function testNextCodeEndpoint(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice, 'Tomate Cerise', 'TC');
        $this->makeGraine($alice, $gt, 'TC1');
        $this->client->loginUser($alice);

        $data = $this->json('GET', '/api/graines/next-code?graineType='.$gt->getId());
        $this->assertSame('TC2', $data['code']);
    }

    public function testCreateWithoutGraineTypeReturns422(): void
    {
        $alice = $this->createUser('alice');
        $this->client->loginUser($alice);

        $data = $this->json('POST', '/api/graines', ['name' => 'Sweet', 'code' => 'X1']);
        $this->assertResponseStatusCodeSame(422);
        $this->assertArrayHasKey('graineType', $data['errors']);
    }

    public function testDuplicateCodeReturns422(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice);
        $this->makeGraine($alice, $gt, 'TC1');
        $this->client->loginUser($alice);

        $data = $this->json('POST', '/api/graines', ['graineType' => $gt->getId(), 'name' => 'Autre', 'code' => 'TC1']);
        $this->assertResponseStatusCodeSame(422);
        $this->assertArrayHasKey('code', $data['errors']);
    }

    public function testInvalidMethodeReturns422(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice);
        $this->client->loginUser($alice);

        $data = $this->json('POST', '/api/graines', [
            'graineType' => $gt->getId(),
            'name' => 'Sweet',
            'methodeSemisConseillee' => 'godet',
        ]);
        $this->assertResponseStatusCodeSame(422);
        $this->assertArrayHasKey('methodeSemisConseillee', $data['errors']);
    }

    public function testListFilteredByGraineType(): void
    {
        $alice = $this->createUser('alice');
        $gt1 = $this->makeGraineType($alice, 'Tomate Cerise', 'TC');
        $gt2 = $this->makeGraineType($alice, 'Courge', 'CG');
        $this->makeGraine($alice, $gt1, 'TC1');
        $this->makeGraine($alice, $gt2, 'CG1');
        $this->client->loginUser($alice);

        $list = $this->json('GET', '/api/graines?graineType='.$gt1->getId());
        $this->assertCount(1, $list['items']);
        $this->assertSame('TC1', $list['items'][0]['code']);
    }

    public function testListScopedToOwner(): void
    {
        $alice = $this->createUser('alice');
        $bob = $this->createUser('bob');
        $gtA = $this->makeGraineType($alice, 'Type Alice', 'TA');
        $gtB = $this->makeGraineType($bob, 'Type Bob', 'TB');
        $this->makeGraine($alice, $gtA, 'TA1');
        $this->makeGraine($bob, $gtB, 'TB1');

        $this->client->loginUser($alice);
        $list = $this->json('GET', '/api/graines');
        $codes = array_column($list['items'], 'code');
        $this->assertContains('TA1', $codes);
        $this->assertNotContains('TB1', $codes);
    }

    public function testCannotEditOthers(): void
    {
        $alice = $this->createUser('alice');
        $bob = $this->createUser('bob');
        $gt = $this->makeGraineType($alice);
        $g = $this->makeGraine($alice, $gt, 'TC1');

        $this->client->loginUser($bob);
        $this->client->request(
            'PUT',
            '/api/graines/'.$g->getId(),
            server: ['CONTENT_TYPE' => 'application/json'],
            content: json_encode(['graineType' => $gt->getId(), 'name' => 'Piraté', 'code' => 'TC1']),
        );
        $this->assertResponseStatusCodeSame(403);
    }

    public function testUpdateAndDelete(): void
    {
        $alice = $this->createUser('alice');
        $gt = $this->makeGraineType($alice);
        $g = $this->makeGraine($alice, $gt, 'TC1', 'Sweet');
        $id = $g->getId();
        $this->client->loginUser($alice);

        $updated = $this->json('PUT', '/api/graines/'.$id, [
            'graineType' => $gt->getId(),
            'name' => 'Sweet Million',
            'code' => 'TC1',
        ]);
        $this->assertResponseIsSuccessful();
        $this->assertSame('Sweet Million', $updated['name']);

        $this->client->request('DELETE', '/api/graines/'.$id);
        $this->assertResponseStatusCodeSame(204);

        $this->client->request('GET', '/api/graines/'.$id);
        $this->assertResponseStatusCodeSame(404);
    }
}
